### ISSUE TITLE
Көмектесіңіз, бұл қазақ тілінде жұмыс істемейді

### ISSUE THREAD

**Issue by kosnovakhta** [danzilberdan/WAJoin#2]

**Comment by danzilberdan** [comment]
This is how you can change whatsapp language to english. Try to launch the script after you have changed the language.

    Open WhatsApp.
    Tap More options > Settings > Chats > App Language.
    Select **English**.

**Comment by kosnovakhta** [comment]
> This is how you can change whatsapp language to english. Try to launch the script after you have changed the language.
> 
> ```
> Open WhatsApp.
> Tap More options > Settings > Chats > App Language.
> Select English.
> ```
Дибур

**Comment by danzilberdan** [comment]
Дӯстам, шумо Шатси девона ҳастед, ки ин гап аст
